import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/Sidebar";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative min-h-screen bg-[#ffffff] text-black lg:flex">
          <Sidebar />
          <div className="flex-1 bg-[#ffffff] lg:ml-[270px]">
            <Navbar />
            <div className="p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
